PROJECT_ROOT := $(CURDIR)/../..
export PROJECT_ROOT
include $(PROJECT_ROOT)/src/mk/header.mk
TARGET := rubiks-cube-solver

all: $(OBJECTS) $(TARGET)

include $(PROJECT_ROOT)/src/mk/rules.mk
include $(PROJECT_ROOT)/src/mk/footer.mk
